const data = {
    shifts: [
        {
            //March 13
          "position": "Server",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 3,
          "liquorSales": 10,
          "totalTips": 7.1,
          "barTipOut": 2,
          "hostTipOut": 1
        },
        {
          "position": "Server",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 3,
          "totalTips": 44.67,
          "barTipOut": 2,
          "hostTipOut": 2
        },
        {
          "position": "Bartender",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 4,
          "totalTips": 43.69,
          "hostTipOut": 4
        },
        {
          "position": "Bartender",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 7,
          "totalTips": 13.46
        },
        {
          "position": "Host",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 4.5
        },
        {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 10.25,
            "liquorSales": 607.99,
            "totalTips": 296.34,
            "barTipOut": 50,
            "expoTipOut": 10,
            "hostTipOut": 10
          },
          {
            "position": "Host",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 3.75
          },
          {
            "position": "Bartender",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 7.25,
            "liquorSales": 470.5,
            "totalTips": 67.5,
            "bBackTipOut": 30.39
          },
          {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 7.5,
            "liquorSales": 592,
            "totalTips": 219.42,
            "barTipOut": 40,
            "expoTipOut": 45,
            "hostTipOut": 10
          },
          {
            "position": "Bartender",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 5.5,
            "totalTips": 67.5

          },
          {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 5,
            "liquorSales": 413,
            "totalTips": 198.39,
            "barTipOut": 16,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5,
            "totalTips": 34.7
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 3.25,
            "totalTips": 19.48,
            "barTipOut": 1,
            "bBackTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 3,
            "totalTips": 66.55
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 7,
            "totalTips": 49,
            "hostTipOut": 2
          },
          {
            "position": "Host",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 4.75
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 8,
            "totalTips": 210.29,
            "barTipOut": 40,
            "hostTipOut": 5,
            "expoTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 4.25
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 6,
            "liquorSales": 449,
            "totalTips": 189.21,
            "barTipOut": 17,
            "expoTipOut": 10,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5.25,
            "totalTips": 139.41,
            "bBackTipOut": 17.5,
            "expoTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 7.25,
            "totalTips": 93.31,
            "bBackTipOut": 17.5,
            "expoTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5.75,
            "liquorSales": 511,
            "totalTips": 165.12,
            "barTipOut": 20,
            "expoTipOut": 20,
            "hostTipOut": 5
          }, 
          //March 15
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 14,
            "totalTips": 18.63,
            "barTipOut": 2,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 2
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 8.11,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 14,
            "totalTips": 15.2,
            "barTipOut": 0,
            "bBackTipOut": 2,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 146.6,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 5.5,
            "foodSales": 0,
            "liquorSales": 213.75,
            "totalTips": 124.7,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 520.5,
            "totalTips": 348.9,
            "barTipOut": 50,
            "bBackTipOut": 0,
            "expoTipOut": 9,
            "hostTipOut": 14
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 511,
            "totalTips": 235.97,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-15",
            "hoursWorked": 8.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 122.99,
            "barTipOut": 0,
            "bBackTipOut": 17.5,
            "expoTipOut": 10,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 6.5,
            "foodSales": 0,
            "liquorSales": 670.5,
            "totalTips": 323.96,
            "barTipOut": 33,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 10
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 163.24,
            "barTipOut": 0,
            "bBackTipOut": 17.5,
            "expoTipOut": 10,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 785,
            "totalTips": 322,
            "barTipOut": 25,
            "bBackTipOut": 0,
            "expoTipOut": 25,
            "hostTipOut": 10
          },
          // March 16
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 413,
            "totalTips": 274.02,
            "barTipOut": 45,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 10
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 7.5,
            "foodSales": 0,
            "liquorSales": 702,
            "totalTips": 334.47,
            "barTipOut": 60,
            "bBackTipOut": 0,
            "expoTipOut": 10,
            "hostTipOut": 14
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 163.24,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 7.5,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 42.87,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 7.5,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 9.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 4.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 4.25,
            "foodSales": 0,
            "liquorSales": 424,
            "totalTips": 137.09,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 308,
            "totalTips": 223.91,
            "barTipOut": 15,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 7.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 585,
            "totalTips": 176.07,
            "barTipOut": 25,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 535,
            "totalTips": 322.06,
            "barTipOut": 22,
            "bBackTipOut": 0,
            "expoTipOut": 13,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 147.6,
            "barTipOut": 0,
            "bBackTipOut": 5,
            "expoTipOut": 10,
            "hostTipOut": 3
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 92.41,
            "barTipOut": 0,
            "bBackTipOut": 30,
            "expoTipOut": 10,
            "hostTipOut": 2
          },
          //March 17
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 200,
            "totalTips": 100,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 213.5,
            "totalTips": 106.52,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 135.5,
            "barTipOut": 0,
            "bBackTipOut": 25,
            "expoTipOut": 13,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 24,
            "totalTips": 24.2,
            "barTipOut": 1,
            "bBackTipOut": 0,
            "expoTipOut": 2,
            "hostTipOut": 1
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 39.65,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-17",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 230,
            "totalTips": 47.26,
            "barTipOut": 15,
            "bBackTipOut": 0,
            "expoTipOut": 10,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 294,
            "totalTips": 249.71,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 35.64,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-17",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
    //March 20
    {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 3.45,
        "foodSales": 0,
        "liquorSales": 36,
        "totalTips": 43.55,
        "barTipOut": 4,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 89.01,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 48.55,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-20",
        "hoursWorked": 2.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 9,
        "foodSales": 0,
        "liquorSales": 407,
        "totalTips": 248.34,
        "barTipOut": 35,
        "bBackTipOut": 0,
        "expoTipOut": 6,
        "hostTipOut": 8
      },
      {
        "position": "Host",
        "date": "2024-03-20",
        "hoursWorked": 5.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 4,
        "foodSales": 0,
        "liquorSales": 291.75,
        "totalTips": 117.69,
        "barTipOut": 20,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 242.76,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 536,
        "totalTips": 228.4,
        "barTipOut": 80,
        "bBackTipOut": 0,
        "expoTipOut": 15,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 2.4,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      //March 21
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 11.75,
        "foodSales": 0,
        "liquorSales": 363,
        "totalTips": 181.76,
        "barTipOut": 28,
        "bBackTipOut": 0,
        "expoTipOut": 6,
        "hostTipOut": 6
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 43.81,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 4
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 4,
        "foodSales": 0,
        "liquorSales": 72.5,
        "totalTips": 39.63,
        "barTipOut": 12,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 3
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 70.36,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-21",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 35,
        "totalTips": 40,
        "barTipOut": 5,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 2
      },
      {
        "position": "Host",
        "date": "2024-03-21",
        "hoursWorked": 4.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 442,
        "totalTips": 212.55,
        "barTipOut": 22,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 116.41,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 3,
        "hostTipOut": 2
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 91.6,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 3,
        "hostTipOut": 2
      },
      //March 22
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 202.37,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 118.35,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 482.5,
        "totalTips": 226.29,
        "barTipOut": 40,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 10
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 4.25,
        "foodSales": 0,
        "liquorSales": 328.75,
        "totalTips": 147.21,
        "barTipOut": 16,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 7.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 519.25,
        "totalTips": 228.98,
        "barTipOut": 28,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 12
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 525.25,
        "totalTips": 260.21,
        "barTipOut": 29,
        "bBackTipOut": 0,
        "expoTipOut": 12,
        "hostTipOut": 15
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 881,
        "totalTips": 258.82,
        "barTipOut": 35,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 10
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 69.08,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 146.21,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      //March 23
      ]
}

export default data