const data = {
    shifts: [
        {
            //March 13
          "position": "Server",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 3,
          "liquorSales": 10,
          "totalTips": 7.1,
          "barTipOut": 2,
          "hostTipOut": 1
        },
        {
          "position": "Server",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 3,
          "totalTips": 44.67,
          "barTipOut": 2,
          "hostTipOut": 2
        },
        {
          "position": "Bartender",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 4,
          "totalTips": 43.69,
          "hostTipOut": 4
        },
        {
          "position": "Bartender",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 7,
          "totalTips": 13.46
        },
        {
          "position": "Host",
          "date": "2024-03-13T00:00:00.000Z",
          "hoursWorked": 4.5
        },
        {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 10.25,
            "liquorSales": 607.99,
            "totalTips": 296.34,
            "barTipOut": 50,
            "expoTipOut": 10,
            "hostTipOut": 10
          },
          {
            "position": "Host",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 3.75
          },
          {
            "position": "Bartender",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 7.25,
            "liquorSales": 470.5,
            "totalTips": 67.5,
            "bBackTipOut": 30.39
          },
          {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 7.5,
            "liquorSales": 592,
            "totalTips": 219.42,
            "barTipOut": 40,
            "expoTipOut": 45,
            "hostTipOut": 10
          },
          {
            "position": "Bartender",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 5.5,
            "totalTips": 67.5

          },
          {
            "position": "Server",
            "date": "2024-03-13T00:00:00.000Z",
            "hoursWorked": 5,
            "liquorSales": 413,
            "totalTips": 198.39,
            "barTipOut": 16,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5,
            "totalTips": 34.7
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 3.25,
            "totalTips": 19.48,
            "barTipOut": 1,
            "bBackTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 3,
            "totalTips": 66.55
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 7,
            "totalTips": 49,
            "hostTipOut": 2
          },
          {
            "position": "Host",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 4.75
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 8,
            "totalTips": 210.29,
            "barTipOut": 40,
            "hostTipOut": 5,
            "expoTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 4.25
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 6,
            "liquorSales": 449,
            "totalTips": 189.21,
            "barTipOut": 17,
            "expoTipOut": 10,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5.25,
            "totalTips": 139.41,
            "bBackTipOut": 17.5,
            "expoTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 7.25,
            "totalTips": 93.31,
            "bBackTipOut": 17.5,
            "expoTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-14T00:00:00.000Z",
            "hoursWorked": 5.75,
            "liquorSales": 511,
            "totalTips": 165.12,
            "barTipOut": 20,
            "expoTipOut": 20,
            "hostTipOut": 5
          }, 
          //March 15
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 14,
            "totalTips": 18.63,
            "barTipOut": 2,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 2
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 8.11,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 14,
            "totalTips": 15.2,
            "barTipOut": 0,
            "bBackTipOut": 2,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 146.6,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-15",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 5.5,
            "foodSales": 0,
            "liquorSales": 213.75,
            "totalTips": 124.7,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 520.5,
            "totalTips": 348.9,
            "barTipOut": 50,
            "bBackTipOut": 0,
            "expoTipOut": 9,
            "hostTipOut": 14
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 511,
            "totalTips": 235.97,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-15",
            "hoursWorked": 8.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 122.99,
            "barTipOut": 0,
            "bBackTipOut": 17.5,
            "expoTipOut": 10,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 6.5,
            "foodSales": 0,
            "liquorSales": 670.5,
            "totalTips": 323.96,
            "barTipOut": 33,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 10
          },
          {
            "position": "Bartender",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 163.24,
            "barTipOut": 0,
            "bBackTipOut": 17.5,
            "expoTipOut": 10,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-15",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 785,
            "totalTips": 322,
            "barTipOut": 25,
            "bBackTipOut": 0,
            "expoTipOut": 25,
            "hostTipOut": 10
          },
          // March 16
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 413,
            "totalTips": 274.02,
            "barTipOut": 45,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 10
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 7.5,
            "foodSales": 0,
            "liquorSales": 702,
            "totalTips": 334.47,
            "barTipOut": 60,
            "bBackTipOut": 0,
            "expoTipOut": 10,
            "hostTipOut": 14
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 163.24,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 7.5,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 42.87,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 7.5,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 9.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 4.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 4.25,
            "foodSales": 0,
            "liquorSales": 424,
            "totalTips": 137.09,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 20,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 308,
            "totalTips": 223.91,
            "barTipOut": 15,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Host",
            "date": "2024-03-16",
            "hoursWorked": 7.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 585,
            "totalTips": 176.07,
            "barTipOut": 25,
            "bBackTipOut": 0,
            "expoTipOut": 15,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-16",
            "hoursWorked": 6.75,
            "foodSales": 0,
            "liquorSales": 535,
            "totalTips": 322.06,
            "barTipOut": 22,
            "bBackTipOut": 0,
            "expoTipOut": 13,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 147.6,
            "barTipOut": 0,
            "bBackTipOut": 5,
            "expoTipOut": 10,
            "hostTipOut": 3
          },
          {
            "position": "Bartender",
            "date": "2024-03-16",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 92.41,
            "barTipOut": 0,
            "bBackTipOut": 30,
            "expoTipOut": 10,
            "hostTipOut": 2
          },
          //March 17
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 200,
            "totalTips": 100,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 213.5,
            "totalTips": 106.52,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 135.5,
            "barTipOut": 0,
            "bBackTipOut": 25,
            "expoTipOut": 13,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 3,
            "foodSales": 0,
            "liquorSales": 24,
            "totalTips": 24.2,
            "barTipOut": 1,
            "bBackTipOut": 0,
            "expoTipOut": 2,
            "hostTipOut": 1
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 39.65,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-17",
            "hoursWorked": 7,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 5.25,
            "foodSales": 0,
            "liquorSales": 230,
            "totalTips": 47.26,
            "barTipOut": 15,
            "bBackTipOut": 0,
            "expoTipOut": 10,
            "hostTipOut": 5
          },
          {
            "position": "Server",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 294,
            "totalTips": 249.71,
            "barTipOut": 20,
            "bBackTipOut": 0,
            "expoTipOut": 5,
            "hostTipOut": 5
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 5.5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 35.64,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Host",
            "date": "2024-03-17",
            "hoursWorked": 5,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
          {
            "position": "Bartender",
            "date": "2024-03-17",
            "hoursWorked": 6,
            "foodSales": 0,
            "liquorSales": 0,
            "totalTips": 0,
            "barTipOut": 0,
            "bBackTipOut": 0,
            "expoTipOut": 0,
            "hostTipOut": 0
          },
    //March 20
    {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 3.45,
        "foodSales": 0,
        "liquorSales": 36,
        "totalTips": 43.55,
        "barTipOut": 4,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 89.01,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 48.55,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-20",
        "hoursWorked": 2.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 9,
        "foodSales": 0,
        "liquorSales": 407,
        "totalTips": 248.34,
        "barTipOut": 35,
        "bBackTipOut": 0,
        "expoTipOut": 6,
        "hostTipOut": 8
      },
      {
        "position": "Host",
        "date": "2024-03-20",
        "hoursWorked": 5.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 4,
        "foodSales": 0,
        "liquorSales": 291.75,
        "totalTips": 117.69,
        "barTipOut": 20,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 242.76,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-20",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 536,
        "totalTips": 228.4,
        "barTipOut": 80,
        "bBackTipOut": 0,
        "expoTipOut": 15,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-20",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 2.4,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      //March 21
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 11.75,
        "foodSales": 0,
        "liquorSales": 363,
        "totalTips": 181.76,
        "barTipOut": 28,
        "bBackTipOut": 0,
        "expoTipOut": 6,
        "hostTipOut": 6
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 43.81,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 4
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 4,
        "foodSales": 0,
        "liquorSales": 72.5,
        "totalTips": 39.63,
        "barTipOut": 12,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 3
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 70.36,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-21",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 35,
        "totalTips": 40,
        "barTipOut": 5,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 2
      },
      {
        "position": "Host",
        "date": "2024-03-21",
        "hoursWorked": 4.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-21",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 442,
        "totalTips": 212.55,
        "barTipOut": 22,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 116.41,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 3,
        "hostTipOut": 2
      },
      {
        "position": "Bartender",
        "date": "2024-03-21",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 91.6,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 3,
        "hostTipOut": 2
      },
      //March 22
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 202.37,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 118.35,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 482.5,
        "totalTips": 226.29,
        "barTipOut": 40,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 10
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 4.25,
        "foodSales": 0,
        "liquorSales": 328.75,
        "totalTips": 147.21,
        "barTipOut": 16,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 7.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-03-22",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 519.25,
        "totalTips": 228.98,
        "barTipOut": 28,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 12
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 525.25,
        "totalTips": 260.21,
        "barTipOut": 29,
        "bBackTipOut": 0,
        "expoTipOut": 12,
        "hostTipOut": 15
      },
      {
        "position": "Server",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 881,
        "totalTips": 258.82,
        "barTipOut": 35,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 10
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 69.08,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      {
        "position": "Bartender",
        "date": "2024-03-22",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 146.21,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      //March 23
      {
        "position": "Bartender",
        "date": "2024-03-23",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 159.46,
        "barTipOut": 0,
        "bBackTipOut": 30,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-23",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 256.3,
        "barTipOut": 0,
        "bBackTipOut": 30,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-23",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 565.5,
        "totalTips": 330.92,
        "barTipOut": 50,
        "bBackTipOut": 0,
        "expoTipOut": 40,
        "hostTipOut": 10
      },
      {
        "position": "Host",
        "date": "2024-03-23",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-23",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 506,
        "totalTips": 274.65,
        "barTipOut": 25,
        "bBackTipOut": 0,
        "expoTipOut": 15,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-03-23",
        "hoursWorked": 11.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-23",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 656,
        "totalTips": 283.46,
        "barTipOut": 27,
        "bBackTipOut": 0,
        "expoTipOut": 25,
        "hostTipOut": 15
      },
      {
        "position": "Host",
        "date": "2024-03-23",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-03-23",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 150.59,
        "barTipOut": 0,
        "bBackTipOut": 20,
        "expoTipOut": 5,
        "hostTipOut": 5
      },
      {
        "position": "Server",
        "date": "2024-03-23",
        "hoursWorked": 7.25,
        "foodSales": 0,
        "liquorSales": 609,
        "totalTips": 317.89,
        "barTipOut": 29,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 16
      },
      {
        "position": "Server",
        "date": "2024-03-23",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 808.75,
        "totalTips": 332.7,
        "barTipOut": 43,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 16
      },
      //March 24
      {
        "position": "Bartender",
        "date": "2024-03-24",
        "hoursWorked": 12.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 178.89,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 2
      },
      {
        "position": "Server",
        "date": "2024-03-24",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 373,
        "totalTips": 247.53,
        "barTipOut": 25,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 7
      },
      {
        "position": "Bartender",
        "date": "2024-03-24",
        "hoursWorked": 12.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 190.75,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 44,
        "hostTipOut": 5
      },
      {
        "position": "Server",
        "date": "2024-03-24",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 287,
        "totalTips": 100.43,
        "barTipOut": 10,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-03-24",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-03-24",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 609,
        "totalTips": 317.89,
        "barTipOut": 29,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 5
      },
      //April 3
      {
        "position": "Bartender",
        "date": "2024-04-03",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 59.4,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-03",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 73,
        "totalTips": 125.67,
        "barTipOut": 7,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-03",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-03",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 423,
        "totalTips": 247.1,
        "barTipOut": 22,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-03",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 543,
        "totalTips": 279.46,
        "barTipOut": 22,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 30
      },
      {
        "position": "Bartender",
        "date": "2024-04-03",
        "hoursWorked": 7.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 197.47,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 25
      },
      //April 4
      {
        "position": "Bartender",
        "date": "2024-04-04",
        "hoursWorked": 7.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 121.66,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-04",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 166.5,
        "totalTips": 96.9,
        "barTipOut": 15,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-04",
        "hoursWorked": 5.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-04",
        "hoursWorked": 7.75,
        "foodSales": 0,
        "liquorSales": 93,
        "totalTips": 75.8,
        "barTipOut": 10,
        "bBackTipOut": 0,
        "expoTipOut": 3,
        "hostTipOut": 2
      },
      {
        "position": "Server",
        "date": "2024-04-04",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 500,
        "totalTips": 238.14,
        "barTipOut": 30,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-04-04",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 85.13,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-04",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 85.13,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 0
      },
      //April 5
      {
        "position": "Bartender",
        "date": "2024-04-05",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 106.34,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-05",
        "hoursWorked": 8,
        "foodSales": 0,
        "liquorSales": 305.25,
        "totalTips": 134.12,
        "barTipOut": 20,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-05",
        "hoursWorked": 2.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 12,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-05",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-05",
        "hoursWorked": 9,
        "foodSales": 0,
        "liquorSales": 680,
        "totalTips": 359.25,
        "barTipOut": 34,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 8
      },
      {
        "position": "Host",
        "date": "2024-04-05",
        "hoursWorked": 8.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-05",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 686.75,
        "totalTips": 320,
        "barTipOut": 44,
        "bBackTipOut": 0,
        "expoTipOut": 8,
        "hostTipOut": 16
      },
      {
        "position": "Host",
        "date": "2024-04-05",
        "hoursWorked": 4,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-05",
        "hoursWorked": 8,
        "foodSales": 0,
        "liquorSales": 737,
        "totalTips": 328.95,
        "barTipOut": 30,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 15
      },
      {
        "position": "Bartender",
        "date": "2024-04-05",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 76.55,
        "barTipOut": 0,
        "bBackTipOut": 35,
        "expoTipOut": 7.5,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-05",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 309.9,
        "barTipOut": 0,
        "bBackTipOut": 35,
        "expoTipOut": 7.5,
        "hostTipOut": 0
      },
      {
        "position": "Barback",
        "date": "2024-04-05",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      //April 6
      {
        "position": "Server",
        "date": "2024-04-06",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 390,
        "totalTips": 222.14,
        "barTipOut": 30,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 10
      },
      {
        "position": "Server",
        "date": "2024-04-06",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 488,
        "totalTips": 317.42,
        "barTipOut": 24,
        "bBackTipOut": 0,
        "expoTipOut": 6,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-04-06",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 154.32,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 27,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-06",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 331.61,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 25,
        "hostTipOut": 15
      },
      {
        "position": "Host",
        "date": "2024-04-06",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-06",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-06",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 622,
        "totalTips": 253.84,
        "barTipOut": 31,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-04-06",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 119.26,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 15,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-04-06",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 130.29,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 15,
        "hostTipOut": 5
      },
      {
        "position": "Server",
        "date": "2024-04-06",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 523,
        "totalTips": 226.12,
        "barTipOut": 30,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      //April 7
      {
        "position": "Server",
        "date": "2024-04-07",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 418,
        "totalTips": 206.17,
        "barTipOut": 38,
        "bBackTipOut": 0,
        "expoTipOut": 18,
        "hostTipOut": 10
      },
      {
        "position": "Bartender",
        "date": "2024-04-07",
        "hoursWorked": 7,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 75.42,
        "barTipOut": 0,
        "bBackTipOut": 15,
        "expoTipOut": 25,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-07",
        "hoursWorked": 7.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 346.02,
        "barTipOut": 0,
        "bBackTipOut": 16,
        "expoTipOut": 25,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-07",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Expo",
        "date": "2024-04-07",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-07",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 354.25,
        "totalTips": 236.35,
        "barTipOut": 18,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-04-07",
        "hoursWorked": 4.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-07",
        "hoursWorked": 3.25,
        "foodSales": 0,
        "liquorSales": 146.5,
        "totalTips": 94.41,
        "barTipOut": 7,
        "bBackTipOut": 0,
        "expoTipOut": 2,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-07",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 65.28,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 0
      },
      //April 10
      {
        "position": "Bartender",
        "date": "2024-04-10",
        "hoursWorked": 7.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 58.18,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-10",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 95,
        "totalTips": 63.9,
        "barTipOut": 7,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-10",
        "hoursWorked": 4.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-10",
        "hoursWorked": 5.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-10",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 330,
        "totalTips": 175.94,
        "barTipOut": 15,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      {
        "position": "Bartender",
        "date": "2024-04-10",
        "hoursWorked": 7.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 260.02,
        "barTipOut": 0,
        "bBackTipOut": 50,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      {
        "position": "Server",
        "date": "2024-04-10",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 164,
        "totalTips": 110.71,
        "barTipOut": 10,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 3
      },
      //April 11
      {
        "position": "Server",
        "date": "2024-04-11",
        "hoursWorked": 3.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 43.84,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-11",
        "hoursWorked": 6.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 97.73,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-11",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-11",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 193.5,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-11",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 236.5,
        "totalTips": 120.09,
        "barTipOut": 25,
        "bBackTipOut": 0,
        "expoTipOut": 2,
        "hostTipOut": 5
      },
      {
        "position": "Server",
        "date": "2024-04-11",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 320,
        "totalTips": 163.75,
        "barTipOut": 10,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      //April 12
      {
        "position": "Bartender",
        "date": "2024-04-12",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 63.08,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 3
      },
      {
        "position": "Server",
        "date": "2024-04-12",
        "hoursWorked": 3.25,
        "foodSales": 0,
        "liquorSales": 33.85,
        "totalTips": 54.39,
        "barTipOut": 3,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Host",
        "date": "2024-04-12",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-12",
        "hoursWorked": 4.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 77,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-12",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 189.5,
        "totalTips": 109.52,
        "barTipOut": 9,
        "bBackTipOut": 0,
        "expoTipOut": 2,
        "hostTipOut": 2
      },
      {
        "position": "Host",
        "date": "2024-04-12",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-12",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 98.3,
        "barTipOut": 0,
        "bBackTipOut": 5,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      {
        "position": "Server",
        "date": "2024-04-12",
        "hoursWorked": 7.5,
        "foodSales": 0,
        "liquorSales": 314.5,
        "totalTips": 185.26,
        "barTipOut": 10,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 6.3
      },
      {
        "position": "Barback",
        "date": "2024-04-12",
        "hoursWorked": 1.25,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-12",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 114.46,
        "barTipOut": 0,
        "bBackTipOut": 5,
        "expoTipOut": 5,
        "hostTipOut": 2.5
      },
      {
        "position": "Server",
        "date": "2024-04-12",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 121.5,
        "totalTips": 123.96,
        "barTipOut": 15,
        "bBackTipOut": 0,
        "expoTipOut": 10,
        "hostTipOut": 10
      },
      //April 13
      {
        "position": "Server",
        "date": "2024-04-13",
        "hoursWorked": 6.5,
        "foodSales": 0,
        "liquorSales": 351.75,
        "totalTips": 149.75,
        "barTipOut": 25,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 6
      },
      {
        "position": "Server",
        "date": "2024-04-13",
        "hoursWorked": 5.25,
        "foodSales": 0,
        "liquorSales": 149,
        "totalTips": 109.49,
        "barTipOut": 8,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 2
      },
      {
        "position": "Bartender",
        "date": "2024-04-13",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 158.64,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-04-13",
        "hoursWorked": 4.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-13",
        "hoursWorked": 5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 154.15,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-13",
        "hoursWorked": 8,
        "foodSales": 0,
        "liquorSales": 801.75,
        "totalTips": 402.24,
        "barTipOut": 42,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-13",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 151.5,
        "totalTips": 90.78,
        "barTipOut": 5,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 2
      },
      {
        "position": "Bartender",
        "date": "2024-04-13",
        "hoursWorked": 8,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 163.03,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      //April 14
      {
        "position": "Server",
        "date": "2024-04-14",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 169.5,
        "totalTips": 107.28,
        "barTipOut": 25,
        "bBackTipOut": 0,
        "expoTipOut": 5,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-14",
        "hoursWorked": 6.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 200,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 0,
        "hostTipOut": 10
      },
      {
        "position": "Server",
        "date": "2024-04-14",
        "hoursWorked": 6,
        "foodSales": 0,
        "liquorSales": 830.3,
        "totalTips": 158.94,
        "barTipOut": 20,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 0
      },
      {
        "position": "Server",
        "date": "2024-04-14",
        "hoursWorked": 3.5,
        "foodSales": 0,
        "liquorSales": 169.25,
        "totalTips": 141.81,
        "barTipOut": 16,
        "bBackTipOut": 0,
        "expoTipOut": 20,
        "hostTipOut": 5
      },
      {
        "position": "Host",
        "date": "2024-04-14",
        "hoursWorked": 3.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Expo",
        "date": "2024-04-14",
        "hoursWorked": 3,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 0,
        "barTipOut": 0,
        "bBackTipOut": 0,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      {
        "position": "Bartender",
        "date": "2024-04-14",
        "hoursWorked": 5.75,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 51.83,
        "barTipOut": 0,
        "bBackTipOut": 10,
        "expoTipOut": 0,
        "hostTipOut": 10
      },
      {
        "position": "Bartender",
        "date": "2024-04-14",
        "hoursWorked": 5.5,
        "foodSales": 0,
        "liquorSales": 0,
        "totalTips": 66.51,
        "barTipOut": 0,
        "bBackTipOut": 3,
        "expoTipOut": 0,
        "hostTipOut": 0
      },
      
      ]
}

export default data